name: commit_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sumit1git/AutoCoder
          ref: 118affb6297b8d01413d7305efd18a30e918936f
      - name: Greetings
        run: echo "$(<greeting.txt)"
